[package]
name = "cdc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
time = "0.1.42"
num_cpus = "1.13.0"
crossbeam = "0.8.2"
crossbeam-utils = "0.8.3"